#!/bin/bash

PIDFILE="$HOME/.theater.pid"

if [ "$1" = "down" ] || [ "$SSH_ORIGINAL_COMMAND" == "down" ]; then
	if [ -r $PIDFILE ]; then
		kill $(<"$PIDFILE")
		rm "$PIDFILE"
	else
		killall chrome
	fi
	exit
fi

if [ ! -r "$PIDFILE" ]; then
	export DISPLAY=:0.0
	nohup google-chrome --start-fullscreen --autoplay-policy=no-user-gesture-required "https://plex.tv/web/app" > /dev/null 2>&1 &
	echo $! > "$PIDFILE"
else
	echo "Theater already started."
fi
